services:
  # db-init:
  #   image: postgres:16-alpine
  #   environment:
  #     PGPASSWORD: linhongji123
  #   command: >
  #     psql -h postgres-shared -U alin -tc
  #     "SELECT 1 FROM pg_database WHERE datname='new-api'"
  #     | grep -q 1 || psql -h postgres-shared -U root -c "CREATE DATABASE \"new-api\""
  #   networks:
  #     - shared-db-network
  #   restart: "no"  # 执行完就退出，不重启

  new-api:
    image: calciumion/new-api:latest
    environment:
      - SQL_DSN=postgresql://alin:linhongji123@postgres-shared:5432/new-api
      - REDIS_CONN_STRING=redis://redis
      - TZ=Asia/Shanghai
      - ERROR_LOG_ENABLED=true # 是否启用错误日志记录 (Whether to enable error log recording)
      - BATCH_UPDATE_ENABLED=true 
    depends_on:
      # - db-init
      - redis
    ports:
      - "54731:3000"
    networks:
      # - default
      - new-api-network
      - shared-db-network


  redis:
    image: redis:latest
    container_name: redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - new-api-network

networks:
  new-api-network:
    driver: bridge
  shared-db-network:
    external: true
    name: shared-db-network