services:
  new-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app:ro
      # - go-mod-cache:/root/go/pkg/mod
      # - go-build-cache:/root/.cache/go-build
      # - bun-cache:/root/.bun/install/cache
    environment:
      - SQL_DSN=postgresql://alin:linhongji123@postgres-shared:5432/new-api
      - REDIS_CONN_STRING=redis://redis
      - TZ=Asia/Shanghai
      - ERROR_LOG_ENABLED=true
      - BATCH_UPDATE_ENABLED=true
    depends_on:
      - redis
    ports:
      - "54731:3000"
    networks:
      - new-api-network
      - shared-db-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - new-api-network

volumes:
  go-mod-cache:
  go-build-cache:
  bun-cache:

networks:
  new-api-network:
    driver: bridge
  shared-db-network:
    external: true
    name: shared-db-network
