FROM golang:1.26.1-bookworm

ENV GO111MODULE=on CGO_ENABLED=0
ENV GOEXPERIMENT=greenteagc

EXPOSE 3000
WORKDIR /data

COPY scripts/dev-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]